language: ruby

rvm:
  - 2.4.1

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - psql -c 'create database firefly_test;' -U postgres
  - cp config/database.travis.yml config/database.yml

